language: node_js
node_js:
- '6'
deploy:
  provider: heroku
  app: pacific-island-21522
  api_key:
    secure: rniKCEO7Pa1xXZUZtnlHnO9cqmQO0YFHJkT6cAOgV9sR5VkxMW6jzan6jHFE7ggi1PyW1hM4s9LzeORkmQhpUITfL4F7ro6YdsjcdaXow/eWl8bBD57epmAZFB0+e+voHiMyYtUXTApMHlt21+LW9emrJ1+r+RYTwzCDa/SjyFggIfra2HpDFos5S06E72ycTK3fAlTHZrPrCUKzeiQ348CrxK6Aynyk1ksARiQ2GGTYzOYnv6BMRNsW4u4EQf+qRZMCzEjqvp1PVUdDTpjzpeNKTqMUa2F7uFxYEnm8KWod0wtSTckmedpTqjVPEhDiDltLyMvWQm2OKxlrO7sMKHr2X0JjedJus9AeWH9xrsXIugyDxgWT+jarN5K8qmOwiWb/4mqMNLvd3yiEZkmFD7thj/bFtzjg6+Rjcl4m23ShXwVGMbxIohRonhDN1O1g1UjQSuSzXPH4VvxYWKFr8I8zulL3acCqjFh0RSbqlUu1Wj9hUAhVgPOZGPQNnIUHKKmuTi9QoLprHiOqHBLFAhc1Nd/X/FRF5C+g9739p8p+n9/2QkJxYhWK5UHTyYYiRnDQoxgo1J+Ysfb/mkt3YRWuXFgBSfTLSbk7iLAGKsqK6GTVuSSFpDBqtF30OG9KCT6/ZTNP8W4o0LhQElgYr5uG0Mq8w5zzgJOuJbVWCCQ=
