language: node_js
node_js:
- '6'
deploy:
  provider: heroku
  api_key:
    secure: vscVjnTqtVv7FAspa6l1BLA+70yV3WzdA8n1JIgGTTUSKDhAZTjzWFADqiPMylSqY8uKH1QD6nKTXlSXna7G5Dg6i+DpAHUX1J9LdN0nJRYlyr/ZsUn8dL0kxcDADrPoIQVfoW50GRpPGKN9a0WpIAtWia1n+lEU77rU3h4ZEXJiBiD4ZmCRXZK5R7PqPaGz3nngwRL2215h+IkEpAnr68X9C9o+OtVCVKCZnY3MYYBOQWx48cIyUK38va+RJM7Zl+kl0UDI1m9nn2SfMGhPzg2M1ZDGw1WPapx9Jet2CXppaphjotbfUcKq9QwtXjY/89n308I5rof2p3P4MelvvrT4dt3nbJBUZWfSMwnY5Vu8eVJXdohueWHZuGU/HmAaLudDIWuq4wUFQlF50gKaTkJ5Ms5gh2mLToLI+QuR/HUaAokOk62u0KCvzuojbn9Q+jpEY/pyDmKCnF6XMAmlODdU1FQOfc+ZilF0eB5weh6aL99FKWefSz5kmaWcitLT3fz+91KWIy0r7QsyCQguZM1U86yNxe40Y1t7AiU0IuAl1HFjNQlVKnMl4zZCL+HNaFzyB3siiTl+ZnRyn+WjcBMuKMb/8qV7Hmy/EXie5cTbTRX/Q5jDUiaRdu0FeO7UPhuchAuPOkXwgFkeW41oAb08gPzRATjVxXNhxoaAt6w=
  app: pacific-island-21522
