language: node_js
node_js:
- '6'
deploy:
  provider: heroku
  api_key:
    secure: wpjEEwg6oHXKMP+pmosVd/My9ANFpFudtHMpH0jl8yw3Y4LcTfk9ZyuJ938ppp3QEUViovYgDkPnSXs40Fu7lrnPbgoOzYjlu5ptBzmaQaxTQ/HXb9PbKXSmFjM6wF4iZj4A9hVSIKCbpa7GqElSPROJhMMyMHoayzHAQor8XXn/8z/D2xs80w4iGcqP3fwoSURejgUJvBmnKSrQsaLW9fqQ8yifTHv6deisASZApDAfy08K5S/e7YNXKGOLgjZdJhQdNWcbCpeOn6tcH5sd9JFXfQ13RVVgW+M53y2jSqOhe05AypEuwgHtrttSL4BN3FlV/9dR1TuG7/eu5H2QfBHwc0vC3KW2lrHMkMBNL34FX8y9EGojp9GL6gU5zneOn/uj+xDZ+BtStYjGkyhNQlxk96Eb1e0z9ySDq//kMBJ9SYfaD/sKRP4u1CuUrFlR3Linquf1PHzR6zPhtCHUk4bpNZRz5x4qFI2ZG6ZwUoAC6P8Cf3Inl9GLv7ZWWwGbetqWS+yML5jfpLKFKSvaK8AiyT1CPEZqh0V0PVyhG4iVn2QcrWtV4BoXKdKRJQlTLePq5+aOfVYSWMdR+hphepGpzngPyqXlUzY/vTCzUgG4QR5ZoGH3eX/Y3JDSin74kD41leYcr71Ye08r4ZGLkdpZ7K63yf8EeJgjHtZxKXY=
  app: pacific-island-21522
