language: node_js
node_js:
- '6'
deploy:
  provider: heroku
  api_key:
    secure: R62ZF1zulT4gY7EE+SjRpcxbXTFDVUJUhZLiD4CfOziJhG23gq5VEgZs0nhUzrwAqt0ywm1Pvk22whA42lfiUfaRrA01/Pc1eAqe2+Td97jFinlOkBdSOm3FNEAhhjgx+kR0E/tJMdRLb9kDulXqflGK85tFHZgpi5MN+ftkQX9pvifHtG3bvgzAe5wZRIRXxL5FZW1WGKPJlyfyJXZhXm/RkDlZVuvYIe0M9wISeVKSw1KP4noVGA0m6oqWIx7XKkkNEXHGi4QTRKw2pc0BeMBYhLGVt/6xsfDNMZRoSJo7h153COOGDKWokGt/aiMcA26xNDaytIuNsEQdbhG7Lkc0+NyE78cclpOyjJfG469ux/sLb9wdi7f9GtdsTEF6UHrmJbl+67DJtbojJKVNWjKTr1bEVG1R0KPpIk4RIBvfhnEyTrt7z/nFjWpyr8QbHgD8x0NtGsn6IShL69cz+UTfjU55oQ6Dl67mPcZfg5PvgdUTToZ5GRXNCcwp40XwKHlRkdUIJDKXcTosrYp/cyFAY8tTtfcOAEfsseMrnZQvkboB0DZA973uPrra4MWoqQZrGPtjbX0Vwg3KUZsExGD7sC6+JCiL7u0eMEC2mXvCao4ocyugwOXVjj5eT5fLHu0GZSB0u4tkBIAzcuGjyBZTKHd2qKF59PvFusevJgE=
  app: pacific-island-21522
  on:
    repo: iNata/shri-hw-6
